#include"config.h"
#include"discrete_variable_representation.h"
#include"log.h"
#include"oscillator.h"
#include"podvr.h"
#include"representation.h"
// #include"rotation.h"
#include"sincdvr.h"
#include"stationary_state.h"
